Resources:
  BackendTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${COPILOT_SERVICE_NAME}-table"
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
